spring.application.name=dermaponte-backend
server.address=127.0.0.1
server.port=8080
server.error.include-message=never
server.error.include-stacktrace=never
spring.security.user.name=${DERMAPONTE_USER:developer}
spring.security.user.password=${DERMAPONTE_PASSWORD}
