# Generated by Django 5.2.5 on 2026-08-25 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('patient_name', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('city', models.CharField(max_length=80, verbose_name='Cidade')),
                ('state', models.CharField(default='SP', max_length=2, verbose_name='UF')),
                ('lesion_location', models.CharField(max_length=120, verbose_name='Local da lesão')),
                ('noticed_when', models.CharField(max_length=120, verbose_name='Quando percebeu a lesão?')),
                ('changed', models.BooleanField(default=False, verbose_name='Mudou de tamanho, formato ou cor?')),
                ('bleeding', models.BooleanField(default=False, verbose_name='Sangra?')),
                ('itching_or_pain', models.BooleanField(default=False, verbose_name='Coça ou dói?')),
                ('not_healing', models.BooleanField(default=False, verbose_name='Não cicatriza há quatro semanas?')),
                ('personal_history', models.BooleanField(default=False, verbose_name='Histórico pessoal de câncer de pele?')),
                ('family_history', models.BooleanField(default=False, verbose_name='Histórico familiar de câncer de pele?')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('image', models.ImageField(upload_to='cases/', verbose_name='Foto da lesão')),
                ('consent', models.BooleanField(default=False, verbose_name='Consentimento')),
                ('priority', models.CharField(choices=[('urgent', 'Revisão prioritária'), ('soon', 'Revisão breve'), ('routine', 'Revisão de rotina')], default='routine', max_length=10)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('reasons', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('waiting', 'Aguardando revisão'), ('reviewed', 'Revisado'), ('scheduled', 'Consulta agendada')], default='waiting', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('crm', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(default='SP', max_length=2)),
                ('address', models.CharField(max_length=180)),
                ('next_available', models.DateTimeField()),
                ('telemedicine', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='triage.case')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='triage.doctor')),
            ],
        ),
    ]
